version: '3.8'

services:
  directus_redis:
    image: redis:latest
    container_name: directus_redis
    ports:
      - "6379:6379"
    networks:
      - backend

  directus:
    image: directus/directus:11.0.1
    container_name: directus
    environment:
      - KEY=${KEY}
      - SECRET=${SECRET}
      - DB_CLIENT=${DB_CLIENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CACHE_ENABLED=${CACHE_ENABLED}
      - CACHE_STORE=${CACHE_STORE}
      - CACHE_AUTO_PURGE=${CACHE_AUTO_PURGE}
      - REDIS=${REDIS}
    ports:
      - "8055:8055"
    volumes:
      - directus_data:/var/lib/directus
    depends_on:
      - directus_redis
    # TODO: set up depends on with an override
    #   - postgres
    networks:
      - web
      - backend
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.directus.rule=Host(`directus.localhost`)"
    #   - "traefik.http.services.directus.loadbalancer.server.port=8055"

networks:
  web:
    external: true
  backend:
    external: true

volumes:
  directus_data:
    driver: local