version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.53.2
    container_name: n8n
    environment:
      - N8N_PORT=${N8N_PORT}
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    # TODO: set up depends on with an override
    # depends_on:
    #   - postgres
    networks:
      - web
      - backend
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.n8n.rule=Host(`n8n.localhost`)"
    #   - "traefik.http.services.n8n.loadbalancer.server.port=5678"

networks:
  web:
    external: true
  backend:
    external: true

volumes:
  n8n_data:
    driver: local